### PR TITLE
Change sphinx theme

### PR DESCRIPTION
**Pull request by IceBytes**

### CODE REVIEW

**Comment by z44d** [comment]
I have to take a look into it before, if it's have a good style, this pr will be merged.

**Comment by mhdeiiking** [comment]
@IceBytes Good

**Comment by mhdeiiking** [comment]
@mhdeiiking Lol

**Comment by mhdeiiking** [comment]
@mhdeiiking Lol

**Comment by mhdeiiking** [comment]
@mhdeiiking Lol

**Comment by mhdeiiking** [comment]
@mhdeiiking Pol

**Comment by mhdeiiking** [comment]
@mhdeiiking Lol

**Comment by mhdeiiking** [comment]
@mhdeiiking Lol

**Comment by z44d** [comment]
Screenshot from 2024-09-17 22-49-35
it's look sucks, only black and white, not colors etc.., and this jetbrains nerd font remembered me when i was newbie with PyCharm.

**Comment by mhdeiiking** [comment]
@z44d Lol

**Comment by z44d** [comment]
@mhdeiiking @mhdeiiking can you please stop spamming "Lol", thanks.

**Pull request closed without merging**
