### PR TITLE
Improve cli

### PR DESCRIPTION
**Pull request by IceBytes**

### CODE REVIEW

**Comment by IceBytes** [comment]
4 days ago (:

**Comment by z44d** [comment]
Thanks, sorry for replying you too late, this PR is under testing rn :D

**Comment by z44d** [comment]
image

Why there is a `dictionary` of same key, value items.

**Comment by mhdeiiking** [comment]
@z44d illuminators

**Comment by IceBytes** [comment]
2 weeks ago

**Comment by z44d** [comment]
Temporary.

**Pull request closed without merging**
